#!/usr/bin/env bash
# Launch the campus_ws runtime stack in a 2x2 terminator layout.
#
#   +---------------------------+---------------------------+
#   | planner   (auto-run)      | rosserial (auto-run)      |
#   |  conda stp3_ros           |  system ROS python        |
#   +---------------------------+---------------------------+
#   | keyboard  (auto-run)      | mpc       (NOT run)       |
#   |  system ROS python        |  pre-loaded in history    |
#   +---------------------------+---------------------------+
#
# Every pane keeps an interactive bash alive and seeds its command into that
# shell's history, so Ctrl-C followed by Up-arrow + Enter re-runs the node.

set -u

WS="$HOME/campus_ws"
PI="$WS/path_inference"
CONDA_ENV="stp3_ros"
SERIAL_PORT="${SERIAL_PORT:-/dev/ttyACM0}"

GEN_DIR="$HOME/.cache/campus_launcher"
CONF="$GEN_DIR/terminator.conf"
LAYOUT="campus"

# --dry-run: only generate the config/rcfiles, do not start terminator.
DRY_RUN=no
[ "${1:-}" = "--dry-run" ] && DRY_RUN=yes

# --- pane definitions: title | workdir | prep | command | autorun -------------
# prep runs before the command and is NOT put into history (cd/conda live here,
# so Up-arrow gives back the bare command only).
declare -a P_TITLE P_DIR P_PREP P_CMD P_AUTO

add_pane() {
    P_TITLE+=("$1"); P_DIR+=("$2"); P_PREP+=("$3"); P_CMD+=("$4"); P_AUTO+=("$5")
}

#        title       workdir  prep                            command                                        autorun
PLANNER_CMD="python realtime_planner_node_ff_VIO_VLM.py _checkpoint:=$PI/real_time_ff/model/0805_hybrid/best-l2-epoch=28-epoch_val_plan_L2=1.2814.ckpt _expected_model_variant:=hybrid _ego_input_mode:=fixed_speed _fixed_speed_mps:=1.0 _segmentation_backend:=twinlitenet _use_depth:=true _use_fp16:=true _save_plots:=true _plot_seg:=true _plot_depth:=true _plot_mode:=realtime"

add_pane "planner"   "$PI/real_time_ff" "conda activate $CONDA_ENV" "$PLANNER_CMD"   yes
add_pane "rosserial" "$WS"    ""                              "rosrun rosserial_python serial_node.py $SERIAL_PORT" yes
add_pane "keyboard"  "$PI"    ""                              "python3 realtime/keyboard_command.py"         yes
add_pane "mpc"       "$WS"    ""                              "roslaunch mpcbitch run_mpc.launch"            no

# --- sanity checks -----------------------------------------------------------
command -v terminator >/dev/null || { echo "[error] terminator not installed"; exit 1; }
if [ "$DRY_RUN" = no ] && [ -z "${DISPLAY:-}${WAYLAND_DISPLAY:-}" ]; then
    echo "[error] no DISPLAY, run this from a desktop session"; exit 1
fi

mkdir -p "$GEN_DIR"

# --- generate one bash rcfile per pane ---------------------------------------
gen_rc() {
    local file="$1" title="$2" workdir="$3" prep="$4" cmd="$5" autorun="$6"

    cat > "$file" <<EOF
# Auto-generated by soturon.sh -- regenerated on every launch, do not edit.
[ -f "\$HOME/.bashrc" ] && source "\$HOME/.bashrc"

cd "$workdir" 2>/dev/null || echo "[warn] cannot cd to $workdir"
$prep

__campus_cmd='$cmd'

# Seed the command into history on the first prompt (history file is fully
# loaded by then, so this lands as the newest entry -> one Up-arrow reaches it).
__campus_prev_pc="\$PROMPT_COMMAND"
__campus_seed() {
    history -s "\$__campus_cmd"
    PROMPT_COMMAND="\$__campus_prev_pc"
}
PROMPT_COMMAND=__campus_seed

PS1="($title) \$PS1"

echo -e "\033[1;36m[$title]\033[0m \$__campus_cmd"
EOF

    if [ "$autorun" = yes ]; then
        cat >> "$file" <<'EOF'
echo -e "\033[0;90m  Ctrl-C to stop, then Up-arrow + Enter to re-run.\033[0m"

eval "$__campus_cmd"
EOF
    else
        cat >> "$file" <<'EOF'
echo -e "\033[1;33m  NOT started on purpose -- press Up-arrow + Enter to launch it.\033[0m"
EOF
    fi
}

for i in "${!P_TITLE[@]}"; do
    gen_rc "$GEN_DIR/rc_${P_TITLE[$i]}.sh" \
           "${P_TITLE[$i]}" "${P_DIR[$i]}" "${P_PREP[$i]}" "${P_CMD[$i]}" "${P_AUTO[$i]}"
done

# --- generate the terminator layout ------------------------------------------
# Pane order in the layout: 0=top-left 1=top-right 2=bottom-left 3=bottom-right
term_block() {
    local idx="$1" name="$2" parent="$3" order="$4"
    cat <<EOF
    [[[$name]]]
      type = Terminal
      parent = $parent
      order = $order
      profile = default
      title = ${P_TITLE[$idx]}
      command = bash --rcfile $GEN_DIR/rc_${P_TITLE[$idx]}.sh -i
EOF
}

{
cat <<EOF
[global_config]
  suppress_multiple_term_dialog = True
  title_transmit_bg_color = "#2e3436"
[keybindings]
[profiles]
  [[default]]
    cursor_color = "#aaaaaa"
    scrollback_lines = 20000
[layouts]
  [[$LAYOUT]]
    [[[window0]]]
      type = Window
      parent = ""
      order = 0
      maximised = True
      title = campus_ws
    [[[hpane]]]
      type = HPaned
      parent = window0
      order = 0
      position = 800
      ratio = 0.5
    [[[vleft]]]
      type = VPaned
      parent = hpane
      order = 0
      position = 450
      ratio = 0.5
    [[[vright]]]
      type = VPaned
      parent = hpane
      order = 1
      position = 450
      ratio = 0.5
EOF
term_block 0 term_tl vleft  0   # planner    top-left
term_block 2 term_bl vleft  1   # keyboard   bottom-left
term_block 1 term_tr vright 0   # rosserial  top-right
term_block 3 term_br vright 1   # mpc        bottom-right
echo "[plugins]"
} > "$CONF"

echo "[info] layout config : $CONF"
echo "[info] pane rcfiles  : $GEN_DIR/rc_*.sh"
[ "$DRY_RUN" = yes ] && { echo "[info] dry-run, terminator not started"; exit 0; }

# -u / --no-dbus is required: if a terminator instance is already running it
# owns the DBus name, and any new invocation is handed off to that instance,
# which uses its own config and silently ignores -g/-l (you get a blank window).
exec terminator -u -g "$CONF" -l "$LAYOUT"
